### ISSUE TITLE
Incorrect NOAA prediction

### ISSUE THREAD

**Issue by arkangel-dev** [rt-bishop/Look4Sat#130]
The app is reporting an invalid pass. It says there will be a NOAA 15 pass today (5th April 2024) at 18:40 but NOAA 15 is going to be over the atlantic ocean at that time according to both Orbitron AND the apps map. I am located in the Maldives so it shouldn't be predicting that

https://github.com/rt-bishop/Look4Sat/assets/31138457/1e490c13-7b69-4496-ad08-4f5e7ad9e667

**Comment by arkangel-dev** [comment]
Wiping the apps storage and cache fixed. Will report again if it happens again

**Comment by scarlettekk** [comment]
https://github.com/rt-bishop/Look4Sat/issues/126

**Comment by rt-bishop** [comment]
Hey there! I've double and triple checked all the information and can't confirm your observations. I've tested Look4Sat from Google Play with fresh data, GPredict, Orbitron (I thought Look4Sat's UI is not ideal, lol) and N2YO. All the sources show the same data for NOAA 15, 18, 19 and several other satellites. 

Your issue does seem to be connected to #126, but that issue is resolved now and all the calculations are correct. I only left it open for some time to gather people's feedback. I'd suggest to do a clean app install instead of just wiping cache. Apart from that there is not much that can be done, as it shows correct positions and passes on all my devices. And I get confirmations that the app works correctly in several user chats.

![Screenshot (222)](https://github.com/rt-bishop/Look4Sat/assets/44072814/ccd83031-931d-471e-ab23-41918320a37b)
![Screenshot (223)](https://github.com/rt-bishop/Look4Sat/assets/44072814/29ecb743-0d99-44e9-8851-4c1f3989ad71)
![Screenshot (224)](https://github.com/rt-bishop/Look4Sat/assets/44072814/9fade2f1-47ed-4de8-a339-7266fe4f31a7)
![Screenshot_2024-04-07-12-17-16-163_com rtbishop look4sat](https://github.com/rt-bishop/Look4Sat/assets/44072814/03513087-9302-476d-bfbf-0e36eeb36187)
![Screenshot_2024-04-07-12-17-31-710_com rtbishop look4sat](https://github.com/rt-bishop/Look4Sat/assets/44072814/608f0b95-e217-4965-8eaa-a1c5d5c455a2)
![Screenshot_2024-04-07-12-17-59-955_com rtbishop look4sat](https://github.com/rt-bishop/Look4Sat/assets/44072814/1090aa83-e6ea-4ffd-bfe1-3b8df4b8c63c)
![Screenshot_2024-04-07-12-18-03-715_com rtbishop look4sat](https://github.com/rt-bishop/Look4Sat/assets/44072814/91d6713a-2049-453b-b128-9f589145bda6)

**Comment by mklemmingen** [comment]
I can confirm that the bug exists. I succesfully use it on an android smartphone, but doing the same on a samsung tab yields the same bug as of arkangel. All settings are the exact same, and wiping both app data, as well as on another occasion the satellite data did not fix the bug. Reinstalling did also not fix it.

**Comment by mklemmingen** [comment]
Context: 

on the tablet:
![photo_tablet](https://github.com/rt-bishop/Look4Sat/assets/104225647/939d0441-e918-4b8f-bdae-4d7a7d2a91f3)

on the smartphone:
![photo_smartphone](https://github.com/rt-bishop/Look4Sat/assets/104225647/e749fac9-2537-42ad-ae99-63949f6c5fa5)

**Comment by scarlettekk** [comment]
Is the tablet maybe running an old version of the app with the leap day bug sources in it?

**Comment by mklemmingen** [comment]
Good point, I checked, and it does run 3.1.3 instead of 3.1.4. My repos were not up to date. Thank you for the quick resolve. Much appreciated

**Comment by scarlettekk** [comment]
@arkangel-dev can you also ensure you are on version 3.1.4?

**Comment by arkangel-dev** [comment]
sorry, I was on vacation. Yes it is on 3.1.4 @scarlettekk

**Comment by arkangel-dev** [comment]
I'll let you know if this happens again
